import { WasteCategoryRate, RewardItem, ClassProfile } from '../types/index.ts';

export const WASTE_CATEGORIES: WasteCategoryRate[] = [
  {
    category: 'Plastik & Botol',
    pointsPerKg: 25,
    pricePerKg: 2500,
    icon: 'Bottle',
    color: 'from-amber-500 to-orange-500',
  },
  {
    category: 'Kertas & Karton',
    pointsPerKg: 15,
    pricePerKg: 1500,
    icon: 'FileText',
    color: 'from-blue-500 to-indigo-500',
  },
  {
    category: 'Logam & Kaleng',
    pointsPerKg: 50,
    pricePerKg: 6000,
    icon: 'Disc',
    color: 'from-slate-500 to-zinc-600',
  },
  {
    category: 'Minyak Jelantah',
    pointsPerKg: 40,
    pricePerKg: 5000,
    icon: 'Droplets',
    color: 'from-yellow-500 to-amber-600',
  },
  {
    category: 'Elektronik / E-Waste',
    pointsPerKg: 80,
    pricePerKg: 10000,
    icon: 'Cpu',
    color: 'from-purple-500 to-violet-600',
  },
  {
    category: 'Anorganik Lainnya',
    pointsPerKg: 10,
    pricePerKg: 1000,
    icon: 'Package',
    color: 'from-emerald-500 to-teal-600',
  },
];

export const REWARD_ITEMS: RewardItem[] = [
  {
    id: 'reward-cleaning-kit',
    title: 'Paket Sapu, Pengki & Kemoceng Kelas',
    description: '1 Set alat kebersihan kelas baru untuk menjaga kebersihan ruang belajar.',
    category: 'cleaning',
    pointsCost: 150,
    cashCost: 25000,
    icon: 'Sparkles',
  },
  {
    id: 'reward-plants',
    title: '3 Pot Tanaman Lidah Mertua (Sansevieria)',
    description: 'Tanaman pembersih udara dan estetika hijau untuk pojok kelas.',
    category: 'plants',
    pointsCost: 250,
    cashCost: 40000,
    icon: 'Trees',
  },
  {
    id: 'reward-cash-50',
    title: 'Pencairan Kas Kelas Tunai Rp 50.000',
    description: 'Saldo dicairkan ke kas bendahara kelas untuk kebutuhan operasional kelas.',
    category: 'cash',
    pointsCost: 300,
    cashCost: 50000,
    icon: 'Banknote',
  },
  {
    id: 'reward-trash-bin',
    title: 'Tempat Sampah Pilah 2 Kompartemen',
    description: 'Tempat sampah pemilah organik & anorganik dengan stiker edukasi.',
    category: 'facility',
    pointsCost: 500,
    cashCost: 75000,
    icon: 'Trash2',
  },
  {
    id: 'reward-cash-100',
    title: 'Pencairan Kas Kelas Tunai Rp 100.000',
    description: 'Pencairan kas kelas lebih besar untuk acara kelas atau kas tahunan.',
    category: 'cash',
    pointsCost: 600,
    cashCost: 100000,
    icon: 'Wallet',
  },
  {
    id: 'reward-canteen-150',
    title: 'Voucher Kantin Sehat Rp 150.000',
    description: 'Voucher makan bersama satu kelas di kantin adiwiyata sekolah.',
    category: 'canteen',
    pointsCost: 850,
    cashCost: 150000,
    icon: 'Coffee',
  },
];

export const INITIAL_CLASSES: ClassProfile[] = [
  {
    classId: 'X-MIPA-1',
    name: 'X MIPA 1 (Green Earth)',
    points: 380,
    balance: 55000,
    totalWeightKg: 28.5,
    pin: '1011',
    representative: 'Nadia Putri (Ketua Kelas)',
  },
  {
    classId: 'X-MIPA-2',
    name: 'X MIPA 2 (Eco Warrior)',
    points: 520,
    balance: 82000,
    totalWeightKg: 41.2,
    pin: '1022',
    representative: 'Rian Pratama (Sie Lingkungan)',
  },
  {
    classId: 'XI-MIPA-1',
    name: 'XI MIPA 1 (Nature Guardians)',
    points: 740,
    balance: 115000,
    totalWeightKg: 58.7,
    pin: '1111',
    representative: 'Aisyah Zahra (Ketua Kelas)',
  },
  {
    classId: 'XI-IPS-1',
    name: 'XI IPS 1 (Zero Waste)',
    points: 290,
    balance: 42000,
    totalWeightKg: 22.0,
    pin: '1121',
    representative: 'Budi Santoso (Sie Kebersihan)',
  },
  {
    classId: 'XII-MIPA-1',
    name: 'XII MIPA 1 (Adiwiyata Squad)',
    points: 620,
    balance: 96000,
    totalWeightKg: 49.0,
    pin: '1211',
    representative: 'Dimas Anggara (Ketua Kelas)',
  },
  {
    classId: 'XII-IPS-2',
    name: 'XII IPS 2 (Green Champions)',
    points: 440,
    balance: 67000,
    totalWeightKg: 34.5,
    pin: '1222',
    representative: 'Citra Kirana (Sie Lingkungan)',
  },
];
